AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ClusterName:
    Type: String
  TagDomain:
    Type: String
  TagClass:
    Type: String
    AllowedValues:
      - primary
      - secondary
      - utility
      - all
  TagEnv:
    Type: String
    Default: ""
    AllowedValues:
      - production
      - staging
      - "" # Allows the "empty" selection

Conditions:
  HasEnvTag: !Not [!Equals [!Ref TagEnv, ""]]

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
      Tags:
        - Key: domain
          Value: !Ref TagDomain
        - Key: class
          Value: !Ref TagClass
        - !If
          - HasEnvTag
          - Key: env
            Value: !Ref TagEnv
          - !Ref AWS::NoValue

Outputs:
  ClusterName:
    Description: The created cluster
    Value: !Ref ECSCluster
    Export:
      Name: !Sub ${AWS::StackName}-Cluster
